# Generated by Django 4.2.25 on 2025-12-07 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_cita_unique_cita_paciente_fecha_hora'),
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodiario',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='citas.cita'),
        ),
        migrations.AddConstraint(
            model_name='registrodiario',
            constraint=models.UniqueConstraint(fields=('cita', 'fecha'), name='unique_registro_cita_fecha'),
        ),
    ]
