# Generated by Django 4.2.27 on 2025-12-14 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_registrodiario_cita_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodiario',
            name='adherencia',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
