# Generated by Django 4.2.27 on 2025-12-14 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_rename_psico_to_nutricion'),
        ('registros', '0004_alter_registrodiario_adherencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAlimenticio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('carbohidratos_g', models.PositiveIntegerField(blank=True, null=True)),
                ('proteinas_g', models.PositiveIntegerField(blank=True, null=True)),
                ('verduras_porciones', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('frutas_porciones', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grasas_g', models.PositiveIntegerField(blank=True, null=True)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='citas.cita')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
