# Generated by Django 4.2.25 on 2025-11-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='enfoque_terapeutico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='objetivo_terapeutico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='plan_intervencion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='tareas_iniciales',
            field=models.TextField(blank=True, null=True),
        ),
    ]
