# Generated by Django 4.2.25 on 2025-12-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_cita_enfoque_terapeutico_cita_objetivo_terapeutico_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(fields=('paciente', 'fecha', 'hora'), name='unique_cita_paciente_fecha_hora'),
        ),
    ]
